#!/usr/bin/env bash

cap production app:disable

ssh deploy@Mozdm 'sudo stop MozDM'

ssh deploy@Mozdm 'killall -9 ruby'

ssh deploy@Mozdm 'cd a/Mozdm/current ; script/recsv build'

ssh deploy@Mozdm 'sudo start MozDM'

sleep 2

cap production app:enable

echo '----- system is enabled'

alert ding

sleep 5

ssh deploy@Mozdm 'cd a/Mozdm/current ; script/reavatar'

echo '---done'

alert ring
