default: &default
  adapter: postgresql
  encoding: UTF8
  template: template_base
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: mozdm_development

test:
  <<: *default
  database: mozdm_test

production:
  <<: *default
  database: mozdm_production
